import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '@components/base/navbar'
import Footer from '@components/base/footer/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} overflow-x-hidden max-w-screen`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
